<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-Saga-b13ddc3e-d335-42bc-9ed0-b9dbedd52c58</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MassTransit" Version="8.5.5" />
        <PackageReference Include="MassTransit.EntityFrameworkCore" Version="8.5.5" />
        <PackageReference Include="MassTransit.Extensions.DependencyInjection" Version="7.3.1" />
        <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.5" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.10">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.10" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Consumers\" />
      <Folder Include="Services\" />
    </ItemGroup>
</Project>
